services:
  # ================================
  # INFRASTRUCTURE
  # ================================

  mongodb:
    image: mongo:7.0
    container_name: emailight-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_APP_USERNAME: ${MONGO_APP_USERNAME}
      MONGO_APP_PASSWORD: ${MONGO_APP_PASSWORD}
    volumes:
      - mongodb_data:/data/db
      - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - "${MONGO_PORT}:27017"
    networks:
      - emailight-network

  redis:
    image: redis:7.2-alpine
    container_name: emailight-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/etc/redis/redis.conf:ro
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - emailight-network

  # ================================
  # GLITCHTIP - ERROR MONITORING
  # ================================

  postgres:
    image: postgres:17
    container_name: emailight-postgres
    restart: unless-stopped
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: ${GLITCHTIP_POSTGRES_DB}
      POSTGRES_USER: ${GLITCHTIP_POSTGRES_USER}
      POSTGRES_PASSWORD: ${GLITCHTIP_POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${GLITCHTIP_POSTGRES_PORT}:5432"
    networks:
      - emailight-network

  glitchtip-redis:
    image: valkey/valkey
    container_name: emailight-glitchtip-redis
    restart: unless-stopped
    ports:
      - "${GLITCHTIP_REDIS_PORT}:6379"
    networks:
      - emailight-network

  glitchtip-web:
    image: glitchtip/glitchtip
    container_name: emailight-glitchtip-web
    restart: unless-stopped
    depends_on:
      - postgres
      - glitchtip-redis
    ports:
      - "${GLITCHTIP_WEB_PORT}:8000"
    environment:
      DATABASE_URL: postgres://${GLITCHTIP_POSTGRES_USER}:${GLITCHTIP_POSTGRES_PASSWORD}@postgres:5432/${GLITCHTIP_POSTGRES_DB}
      SECRET_KEY: ${GLITCHTIP_SECRET_KEY}
      PORT: 8000
      EMAIL_URL: ${GLITCHTIP_EMAIL_URL}
      GLITCHTIP_DOMAIN: ${GLITCHTIP_DOMAIN}
      DEFAULT_FROM_EMAIL: ${GLITCHTIP_FROM_EMAIL}
      CELERY_WORKER_AUTOSCALE: "1,3"
      REDIS_URL: redis://glitchtip-redis:6379/0
    volumes:
      - glitchtip_uploads:/code/uploads
    networks:
      - emailight-network

  glitchtip-worker:
    image: glitchtip/glitchtip
    container_name: emailight-glitchtip-worker
    restart: unless-stopped
    command: ./bin/run-celery-with-beat.sh
    depends_on:
      - postgres
      - glitchtip-redis
    environment:
      DATABASE_URL: postgres://${GLITCHTIP_POSTGRES_USER}:${GLITCHTIP_POSTGRES_PASSWORD}@postgres:5432/${GLITCHTIP_POSTGRES_DB}
      SECRET_KEY: ${GLITCHTIP_SECRET_KEY}
      PORT: 8000
      EMAIL_URL: ${GLITCHTIP_EMAIL_URL}
      GLITCHTIP_DOMAIN: ${GLITCHTIP_DOMAIN}
      DEFAULT_FROM_EMAIL: ${GLITCHTIP_FROM_EMAIL}
      CELERY_WORKER_AUTOSCALE: "1,3"
      REDIS_URL: redis://glitchtip-redis:6379/0
    volumes:
      - glitchtip_uploads:/code/uploads
    networks:
      - emailight-network

  glitchtip-migrate:
    image: glitchtip/glitchtip
    container_name: emailight-glitchtip-migrate
    command: ./bin/run-migrate.sh
    depends_on:
      - postgres
      - glitchtip-redis
    environment:
      DATABASE_URL: postgres://${GLITCHTIP_POSTGRES_USER}:${GLITCHTIP_POSTGRES_PASSWORD}@postgres:5432/${GLITCHTIP_POSTGRES_DB}
      SECRET_KEY: ${GLITCHTIP_SECRET_KEY}
      EMAIL_URL: ${GLITCHTIP_EMAIL_URL}
      GLITCHTIP_DOMAIN: ${GLITCHTIP_DOMAIN}
      DEFAULT_FROM_EMAIL: ${GLITCHTIP_FROM_EMAIL}
      REDIS_URL: redis://glitchtip-redis:6379/0
    networks:
      - emailight-network

  # ================================
  # ADMIN INTERFACES
  # ================================

  mongo-express:
    image: mongo-express:latest
    container_name: emailight-mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    depends_on:
      - mongodb
    networks:
      - emailight-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: emailight-redis-commander
    restart: unless-stopped
    environment:
      REDIS_HOSTS: "local:redis:6379:0:${REDIS_PASSWORD}"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      HTTP_USER: ${REDIS_COMMANDER_USER}
      HTTP_PASSWORD: ${REDIS_COMMANDER_PASSWORD}
    ports:
      - "${REDIS_COMMANDER_PORT}:8081"
    depends_on:
      - redis
    networks:
      - emailight-network

  # ================================
  # MICROSERVICES
  # ================================

  user-service:
    build: ../user-service
    container_name: emailight-user-service
    restart: unless-stopped
    ports:
      - "${USER_SERVICE_PORT:-3001}:3001"
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      USER_SERVICE_PORT: 3001
      HOST: 0.0.0.0
      
      # MongoDB (utilise les vraies variables d'env)
      MONGODB_URI: mongodb://${MONGO_APP_USERNAME}:${MONGO_APP_PASSWORD}@mongodb:27017/${MONGO_DATABASE}
      
      # JWT & Security
      JWT_SECRET: ${JWT_SECRET:-your_super_secret_jwt_key_change_in_production}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-24h}
      BCRYPT_ROUNDS: ${BCRYPT_ROUNDS:-12}
      TOKEN_ENCRYPTION_KEY: ${TOKEN_ENCRYPTION_KEY:-your-32-character-secret-key-here}
      
      # Rate Limiting
      RATE_LIMIT_MAX: ${RATE_LIMIT_MAX:-100}
      RATE_LIMIT_WINDOW: ${RATE_LIMIT_WINDOW:-60000}
      
      # Redis (utilise le redis du compose)
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis:6379/0
      
      # Logging
      ENABLE_LOGGING: ${ENABLE_LOGGING:-true}
      LOG_LEVEL: ${LOG_LEVEL:-debug}
      VERBOSE_LOGS: ${VERBOSE_LOGS:-true}
      
      # GlitchTip (utilise la même instance)
      GLITCHTIP_DSN: ${USER_SERVICE_GLITCHTIP_DSN:-}
      GLITCHTIP_TRACES_SAMPLE_RATE: ${GLITCHTIP_TRACES_SAMPLE_RATE:-0.1}
      
      # Localisation
      LOCALE: ${LOCALE:-fr-FR}
      TIMEZONE: ${TIMEZONE:-Europe/Paris}
    
    depends_on:
      - mongodb
      - redis
      - glitchtip-web
    
    volumes:
      # Hot reload en développement
      - ../user-service/src:/usr/src/app/src:ro
      # Logs persistants
      - user_service_logs:/usr/src/app/logs
    
    networks:
      - emailight-network
    
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/health', (res) => process.exit(res.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

# ====================
# VOLUMES PERSISTANTS
# ====================
volumes:
  mongodb_data:
    labels:
      - emailight
  redis_data:
    labels:
      - emailight
  postgres_data:
    labels:
      - emailight
  glitchtip_uploads:
    labels:
      - emailight
  user_service_logs:
    labels:
      - emailight

# ====================
# RÉSEAU DU PROJET
# ====================
networks:
  emailight-network:
    name: emailight-network
    driver: bridge