services:
  # ================================
  # INFRASTRUCTURE
  # ================================

  mongodb:
    image: mongo:7.0
    container_name: emailight-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_APP_USERNAME: ${MONGO_APP_USERNAME}
      MONGO_APP_PASSWORD: ${MONGO_APP_PASSWORD}
    volumes:
      - mongodb_data:/data/db
      - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - "${MONGO_PORT}:27017"
    networks:
      - emailight-network

  redis:
    image: redis:7.2-alpine
    container_name: emailight-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/etc/redis/redis.conf:ro
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - emailight-network

  # ================================
  # EXCEPTIONLESS - ERROR MONITORING
  # ================================

  exceptionless:
    image: exceptionless/exceptionless:latest
    container_name: emailight-exceptionless
    restart: unless-stopped
    ports:
      - "${EXCEPTIONLESS_PORT:-5000}:8080"
    # ✅ Volume Docker Natif UNIQUEMENT (PAS de chemin local)
    volumes:
      - exceptionless_storage:/app/storage
    networks:
      - emailight-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s



  # ================================
  # ADMIN INTERFACES
  # ================================

  mongo-express:
    image: mongo-express:latest
    container_name: emailight-mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    depends_on:
      - mongodb
    networks:
      - emailight-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: emailight-redis-commander
    restart: unless-stopped
    environment:
      REDIS_HOSTS: "local:redis:6379:0:${REDIS_PASSWORD}"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      HTTP_USER: ${REDIS_COMMANDER_USER}
      HTTP_PASSWORD: ${REDIS_COMMANDER_PASSWORD}
    ports:
      - "${REDIS_COMMANDER_PORT}:8081"
    depends_on:
      - redis
    networks:
      - emailight-network

  # ================================
  # MICROSERVICES
  # ================================

  user-service:
    build: ../user-service
    container_name: emailight-user-service
    restart: unless-stopped
    ports:
      - "${USER_SERVICE_PORT:-3001}:3001"
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      USER_SERVICE_PORT: 3001
      # 🔥 CORRIGÉ: 0.0.0.0 pour écouter sur toutes les interfaces
      HOST: 0.0.0.0
      
      # MongoDB
      MONGODB_URI: mongodb://${MONGO_APP_USERNAME}:${MONGO_APP_PASSWORD}@mongodb:27017/${MONGO_DATABASE}
      
      # JWT & Security
      JWT_SECRET: ${JWT_SECRET:-your_super_secret_jwt_key_change_in_production}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-24h}
      JWT_REFRESH_EXPIRES_IN: ${JWT_REFRESH_EXPIRES_IN:-7d}
      BCRYPT_ROUNDS: ${BCRYPT_ROUNDS:-12}
      TOKEN_ENCRYPTION_KEY: ${TOKEN_ENCRYPTION_KEY:-your-32-character-secret-key-here}
      
      # Google OAuth
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID:-}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET:-}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI:-http://localhost:3000/auth/google/callback}
      
      # Rate Limiting
      RATE_LIMIT_MAX: ${RATE_LIMIT_MAX:-100}
      RATE_LIMIT_WINDOW: ${RATE_LIMIT_WINDOW:-60000}
      
      # Redis
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis:6379/0
      
      # Logging
      ENABLE_LOGGING: ${ENABLE_LOGGING:-true}
      LOG_LEVEL: ${LOG_LEVEL:-debug}
      VERBOSE_LOGS: ${VERBOSE_LOGS:-true}
      
      # Exceptionless
      USER_SERVICE_EXCEPTIONLESS_API_KEY: ${USER_SERVICE_EXCEPTIONLESS_API_KEY:-}
      USER_SERVICE_EXCEPTIONLESS_SERVER_URL: ${USER_SERVICE_EXCEPTIONLESS_SERVER_URL:-http://exceptionless:8080}
      
      # Localisation
      LOCALE: ${LOCALE:-fr-FR}
      TIMEZONE: ${TIMEZONE:-Europe/Paris}
      
      # 🆕 CORS Configuration (pour résoudre le problème CORS)
      ALLOWED_ORIGINS: "http://localhost:3001,http://127.0.0.1:3001,http://0.0.0.0:3001"
    
    depends_on:
      - mongodb
      - redis
      - exceptionless
    
    volumes:
      # Hot reload en développement
      - ../user-service/src:/usr/src/app/src:ro
      # Logs persistants
      - user_service_logs:/usr/src/app/logs
      - ../user-service/uploads:/usr/src/app/uploads
    
    networks:
      - emailight-network
    
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/health', (res) => process.exit(res.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

# ====================
# VOLUMES PERSISTANTS
# ====================
volumes:
  mongodb_data:
    labels:
      - emailight
  redis_data:
    labels:
      - emailight
  exceptionless_data:
    labels:
      - emailight
  exceptionless_storage:
    labels:
      - emailight
  user_service_logs:
    labels:
      - emailight

# ====================
# RÉSEAU DU PROJET
# ====================
networks:
  emailight-network:
    name: emailight-network
    driver: bridge